[project]
name = "hardware-solvro-bot-office-cam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.11"
dependencies = [
    "numpy>=2.2.5",
    "simplejpeg>=1.8.2",
]
